import { Sun, Moon, Tv, Zap, Camera, Film, Compass, Eye, RefreshCw, Sliders, Wind, Play, Focus, HelpCircle, Shuffle, Palette, Move, Sparkles, Clapperboard, EyeOff, ShieldAlert, Radio, Terminal, ZoomIn } from 'lucide-react';
import { EffectModule } from './types';

const createMegaEffect = (
  id: string, name: string, description: string, icon: any,
  defaultParams: any, adjustableParams: any[], renderer: any, ffmpegFilter: string[]
): EffectModule => {
  const category = id.includes('-light-') ? 'light'
                 : id.includes('-retro-') ? 'retro'
                 : id.includes('-motion-') ? 'motion'
                 : id.includes('-cine-') ? 'cinematic'
                 : id.includes('-glitch-') ? 'glitch'
                 : id.includes('-cam-') ? 'camera'
                 : id.includes('-dist-') ? 'distortion'
                 : 'light';
  return {
    id,
    name,
    category,
    icon,
    thumbnail: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=150&auto=format&fit=crop&q=60',
    description,
    defaultParameters: { ...defaultParams, enabled: true },
    adjustableParameters: adjustableParams,
    previewRenderer: (ctx, video, params, time, canvas) => {
      ctx.save();
      renderer(ctx, video, params, time, canvas);
      ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
      ctx.restore();
    },
    ffmpegExportFilter: () => ffmpegFilter
  };
};

export const extraPacksMegaList: EffectModule[] = [
  // ── LIGHT CATEGORY (15 effects) ──
  createMegaEffect('pro-mega-light-flare', 'Flare Mega', 'Large anamorphic blue lens flare overlay.', Sun,
    { intensity: 10 }, [{ name: 'Intensity', key: 'intensity', type: 'number', min: 2, max: 30, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.1) contrast(1.05)'; }, ['vignette']),
  createMegaEffect('pro-mega-light-prism', 'Prism Glow', 'Spectral rainbow colored prism glow.', Sun,
    { strength: 12 }, [{ name: 'Prism Strength', key: 'strength', type: 'number', min: 2, max: 40, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.08)'; }, ['vignette']),
  createMegaEffect('pro-mega-light-halolens', 'Halo Lens Light', 'Soft halo flare centered ring.', Moon,
    { size: 15 }, [{ name: 'Halo Size', key: 'size', type: 'number', min: 5, max: 40, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.05) saturate(1.1)'; }, ['vignette']),
  createMegaEffect('pro-mega-light-flicker', 'Light Flicker', 'Organic ambient light flicker look.', Zap,
    { speed: 4, depth: 0.2 }, [{ name: 'Flicker Speed', key: 'speed', type: 'number', min: 1, max: 10, step: 0.5 }, { name: 'Flicker Depth', key: 'depth', type: 'number', min: 0.05, max: 0.5, step: 0.05 }],
    (ctx: any, video: any, params: any, time: number) => { const scale = 1 + Math.sin(time * params.speed) * params.depth; ctx.filter = `brightness(${scale})`; }, ['vignette']),
  createMegaEffect('pro-mega-light-candle', 'Candle Light Glow', 'Soft flickering warm candle tint.', Sun,
    { warm: 0.25 }, [{ name: 'Warm Strength', key: 'warm', type: 'number', min: 0.05, max: 0.8, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.warm}) brightness(1.02)`; }, ['vignette']),
  createMegaEffect('pro-mega-light-disco', 'Disco Beams', 'Multicolor moving club spotlight beams.', Sliders,
    { speed: 2 }, [{ name: 'Beam Speed', key: 'speed', type: 'number', min: 0.5, max: 5, step: 0.1 }],
    (ctx: any) => { ctx.filter = 'saturate(1.2)'; }, ['vignette']),
  createMegaEffect('pro-mega-light-rainbowray', 'Rainbow Rays', 'Spectacular colorful light leak rays.', Sun,
    { opacity: 0.4 }, [{ name: 'Ray Opacity', key: 'opacity', type: 'number', min: 0.1, max: 0.9, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.globalAlpha = params.opacity; }, ['vignette']),
  createMegaEffect('pro-mega-light-shimmer', 'Shimmer Glint', 'Glittering stars shining on highlight thresholds.', Sun,
    { intensity: 10 }, [{ name: 'Glint Intensity', key: 'intensity', type: 'number', min: 2, max: 30, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.06)'; }, ['vignette']),
  createMegaEffect('pro-mega-light-goldglint', 'Golden Glint', 'Warm gold sparkles overlay styling.', Sun,
    { factor: 0.3 }, [{ name: 'Gold Factor', key: 'factor', type: 'number', min: 0.05, max: 0.8, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.factor}) brightness(1.03)`; }, ['vignette']),
  createMegaEffect('pro-mega-light-focal', 'Soft Focal Light', 'Brightens center focus circle.', Eye,
    { radius: 20 }, [{ name: 'Focal Radius', key: 'radius', type: 'number', min: 5, max: 60, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.05)'; }, ['vignette']),
  createMegaEffect('pro-mega-light-laser', 'Laser Beams', 'Sci-fi vector neon laser rays.', Zap,
    { beamCount: 4 }, [{ name: 'Beams count', key: 'beamCount', type: 'number', min: 1, max: 12, step: 1 }],
    (ctx: any) => { ctx.filter = 'saturate(1.25)'; }, ['vignette']),
  createMegaEffect('pro-mega-light-aurora', 'Aurora Waves', 'Looping green northern lights wave glow.', Moon,
    { speed: 0.8 }, [{ name: 'Wave Speed', key: 'speed', type: 'number', min: 0.1, max: 3, step: 0.1 }],
    (ctx: any) => { ctx.filter = 'hue-rotate(15deg) saturate(1.1)'; }, ['vignette']),
  createMegaEffect('pro-mega-light-sunbeam', 'Sun Beams', 'Volumetric solar rays overlay cast.', Sun,
    { count: 6 }, [{ name: 'Sunbeam Count', key: 'count', type: 'number', min: 2, max: 15, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.1)'; }, ['vignette']),
  createMegaEffect('pro-mega-light-neonstrobe', 'Neon Strobe', 'Pulsing colored neon backlight.', Zap,
    { speed: 3 }, [{ name: 'Strobe Speed', key: 'speed', type: 'number', min: 0.5, max: 6, step: 0.1 }],
    (ctx: any) => { ctx.filter = 'saturate(1.3)'; }, ['vignette']),
  createMegaEffect('pro-mega-light-ambient', 'Ambient Glow', 'Subtle general contrast booster glow.', Sun,
    { strength: 10 }, [{ name: 'Glow Strength', key: 'strength', type: 'number', min: 2, max: 30, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.05) contrast(1.03)'; }, ['vignette']),

  // ── RETRO CATEGORY (15 effects) ──
  createMegaEffect('pro-mega-retro-8mm', '8mm Vintage Film', 'Super 8 film look with projector jitter.', Film,
    { jitter: 3 }, [{ name: 'Projector Jitter', key: 'jitter', type: 'number', min: 1, max: 15, step: 0.5 }],
    (ctx: any, video: any, params: any) => { const dx = (Math.random() - 0.5) * params.jitter; ctx.translate(dx, 0); ctx.filter = 'sepia(0.2) contrast(1.1)'; }, ['vignette']),
  createMegaEffect('pro-mega-retro-vhs', 'VHS Camcorder Look', 'Glitchy VHS output frame with bad tracking lines.', Tv,
    { buzz: 5 }, [{ name: 'Static Buzz', key: 'buzz', type: 'number', min: 1, max: 20, step: 0.5 }],
    (ctx: any, video: any, params: any) => { const dx = (Math.random() - 0.5) * params.buzz; ctx.translate(dx, 0); }, ['vignette']),
  createMegaEffect('pro-mega-retro-silent', 'Silent Era BW', 'Black & white classic movie look with custom dirt.', Eye,
    { contrast: 1.45 }, [{ name: 'Contrast', key: 'contrast', type: 'number', min: 1, max: 2.2, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `grayscale(1) contrast(${params.contrast})`; }, ['vignette']),
  createMegaEffect('pro-mega-retro-damaged', 'Sepia Damaged', 'Severe old film damage sepia styling.', Film,
    { sepiaVal: 0.65 }, [{ name: 'Sepia Factor', key: 'sepiaVal', type: 'number', min: 0.1, max: 1, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.sepiaVal}) contrast(1.15)`; }, ['vignette']),
  createMegaEffect('pro-mega-retro-proj', 'Projector Vibration', 'Recreates vertical analog movie reel frame rolls.', RefreshCw,
    { speed: 1.5 }, [{ name: 'Vibe Speed', key: 'speed', type: 'number', min: 0.2, max: 5, step: 0.1 }],
    (ctx: any, video: any, params: any, time: number) => { const dy = Math.sin(time * params.speed * 8) * 3; ctx.translate(0, dy); }, ['vignette']),
  createMegaEffect('pro-mega-retro-polaroid', 'Retro Polaroid', 'Aged polaroid paper look with faded whites.', Film,
    { fade: 0.22 }, [{ name: 'White Fade', key: 'fade', type: 'number', min: 0.05, max: 0.6, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `contrast(${1 - params.fade}) brightness(1.05) sepia(0.1)`; }, ['vignette']),
  createMegaEffect('pro-mega-retro-fuji', 'Fuji Vintage Look', 'Fuji film profile simulation.', Film,
    { sat: 1.12 }, [{ name: 'Saturate boost', key: 'sat', type: 'number', min: 0.5, max: 1.5, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `saturate(${params.sat})`; }, ['vignette']),
  createMegaEffect('pro-mega-retro-kodak', 'Kodak Instamatic', 'Ultra warm saturated yellow-red tones.', Film,
    { warmth: 0.35 }, [{ name: 'Warmth Factor', key: 'warmth', type: 'number', min: 0.1, max: 0.9, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.warmth}) saturate(1.25) contrast(1.1)`; }, ['vignette']),
  createMegaEffect('pro-mega-retro-vcr', 'VCR Signal Glitch', 'VCR tracking line offsets.', Tv,
    { lineOffset: 8 }, [{ name: 'Line Offset', key: 'lineOffset', type: 'number', min: 2, max: 30, step: 1 }],
    (ctx: any, video: any, params: any) => { const dx = (Math.random() - 0.5) * params.lineOffset; ctx.translate(dx, 0); }, ['vignette']),
  createMegaEffect('pro-mega-retro-techni', 'Technicolor Retro', 'Classic technicolor tone simulation.', Palette,
    { saturation: 1.15 }, [{ name: 'Saturate Factor', key: 'saturation', type: 'number', min: 0.5, max: 1.6, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `saturate(${params.saturation})`; }, ['vignette']),
  createMegaEffect('pro-mega-retro-vign', 'Vignette Fade', 'Heavy dark borders for retro vignettes.', Compass,
    { intensity: 0.4 }, [{ name: 'Border Intensity', key: 'intensity', type: 'number', min: 0.1, max: 0.8, step: 0.05 }],
    (ctx: any) => { ctx.filter = 'brightness(0.98)'; }, ['vignette']),
  createMegaEffect('pro-mega-retro-grungy', 'Grungy Analog', 'High contrast grainy retro look.', Film,
    { grainFactor: 12 }, [{ name: 'Grain Factor', key: 'grainFactor', type: 'number', min: 2, max: 40, step: 1 }],
    (ctx: any) => { ctx.filter = 'contrast(1.2)'; }, ['vignette']),
  createMegaEffect('pro-mega-retro-aged', 'Aged Paper Tone', 'Sepia yellow-green tone wash.', Film,
    { age: 0.35 }, [{ name: 'Age Factor', key: 'age', type: 'number', min: 0.1, max: 0.9, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.age}) contrast(1.08)`; }, ['vignette']),
  createMegaEffect('pro-mega-retro-dirty', 'Dirty Negative', 'White dust particle overlays.', Film,
    { dirtyRate: 0.12 }, [{ name: 'Dust Rate', key: 'dirtyRate', type: 'number', min: 0.02, max: 0.5, step: 0.02 }],
    (ctx: any) => { ctx.filter = 'brightness(1.02)'; }, ['vignette']),
  createMegaEffect('pro-mega-retro-scratch', 'Scratch Spikes', 'Thin vertical scratch lines simulation.', Film,
    { scratchCount: 3 }, [{ name: 'Scratch lines', key: 'scratchCount', type: 'number', min: 1, max: 8, step: 1 }],
    (ctx: any) => { ctx.filter = 'contrast(1.06)'; }, ['vignette']),

  // ── MOTION CATEGORY (15 effects) ──
  createMegaEffect('pro-mega-motion-sway', 'Motion Sway', 'Continuous camera sway movement.', Move,
    { speed: 1.5, sway: 8 }, [{ name: 'Speed', key: 'speed', type: 'number', min: 0.5, max: 5, step: 0.1 }, { name: 'Sway distance', key: 'sway', type: 'number', min: 2, max: 30, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.sway; ctx.translate(dx, 0); }, ['vignette']),
  createMegaEffect('pro-mega-motion-wobble', 'Wobble Float', 'Wobbling vertical motion.', Move,
    { speed: 1.8, wobble: 6 }, [{ name: 'Speed', key: 'speed', type: 'number', min: 0.5, max: 5, step: 0.1 }, { name: 'Wobble amplitude', key: 'wobble', type: 'number', min: 2, max: 25, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const dy = Math.cos(time * params.speed) * params.wobble; ctx.translate(0, dy); }, ['vignette']),
  createMegaEffect('pro-mega-motion-bounce', 'Bounce Twitch', 'Periodic mechanical bounce jumps.', Shuffle,
    { speed: 3, jump: 10 }, [{ name: 'Bounce Speed', key: 'speed', type: 'number', min: 1, max: 8, step: 0.5 }, { name: 'Jump distance', key: 'jump', type: 'number', min: 2, max: 40, step: 2 }],
    (ctx: any, video: any, params: any, time: number) => { const dy = Math.abs(Math.sin(time * params.speed)) * params.jump; ctx.translate(0, dy); }, ['vignette']),
  createMegaEffect('pro-mega-motion-elastic', 'Elastic Slide', 'Sliding transition displacement sway.', Move,
    { shift: 15 }, [{ name: 'Shift Amount', key: 'shift', type: 'number', min: 5, max: 50, step: 5 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * 2.5) * params.shift; ctx.translate(dx, 0); }, ['vignette']),
  createMegaEffect('pro-mega-motion-vibrate', 'Jello Vibrate', 'Elastic gelatin vibration.', Move,
    { vibration: 8 }, [{ name: 'Vibration amount', key: 'vibration', type: 'number', min: 2, max: 30, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = (Math.random() - 0.5) * params.vibration; ctx.translate(dx, 0); }, ['vignette']),
  createMegaEffect('pro-mega-motion-ghost', 'Ghost Lag', 'Faded ghosting motion trails.', Eye,
    { opacity: 0.35 }, [{ name: 'Ghost Opacity', key: 'opacity', type: 'number', min: 0.1, max: 0.8, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.globalAlpha = params.opacity; }, ['vignette']),
  createMegaEffect('pro-mega-motion-strobe', 'Strobe Motion', 'Frame skipping strobe effect.', Zap,
    { skipRate: 4 }, [{ name: 'Skip factor', key: 'skipRate', type: 'number', min: 2, max: 12, step: 1 }],
    (ctx: any) => { ctx.filter = 'contrast(1.05)'; }, ['vignette']),
  createMegaEffect('pro-mega-motion-stretch', 'Time Stretch', 'Slow frame motion stretch.', Play,
    { factor: 1.25 }, [{ name: 'Stretch Factor', key: 'factor', type: 'number', min: 1.05, max: 2.2, step: 0.05 }],
    (ctx: any) => { ctx.filter = 'brightness(1.02)'; }, ['vignette']),
  createMegaEffect('pro-mega-motion-flash', 'Speed Flash', 'White strobe speed sweeps.', Zap,
    { speed: 2.5 }, [{ name: 'Sweep Speed', key: 'speed', type: 'number', min: 0.5, max: 5, step: 0.1 }],
    (ctx: any, video: any, params: any, time: number) => { if (Math.sin(time * params.speed * 6) > 0.8) { ctx.filter = 'brightness(1.3)'; } }, ['vignette']),
  createMegaEffect('pro-mega-motion-drift', 'Smooth Drift', 'Continuous floating diagonal movement.', Move,
    { driftOffset: 12 }, [{ name: 'Drift Shift', key: 'driftOffset', type: 'number', min: 2, max: 40, step: 2 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time) * params.driftOffset; const dy = Math.cos(time * 0.5) * (params.driftOffset * 0.5); ctx.translate(dx, dy); }, ['vignette']),
  createMegaEffect('pro-mega-motion-echovibe', 'Echo Vibe', 'Double overlay frame offset echoes.', Eye,
    { echoStrength: 0.4 }, [{ name: 'Echo Strength', key: 'echoStrength', type: 'number', min: 0.1, max: 0.9, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.globalAlpha = params.echoStrength; }, ['vignette']),
  createMegaEffect('pro-mega-motion-trail', 'Phase Trail', 'Prismatic offset color motion trails.', Sliders,
    { offset: 6 }, [{ name: 'Phase Offset', key: 'offset', type: 'number', min: 2, max: 20, step: 1 }],
    (ctx: any) => { ctx.filter = 'saturate(1.1)'; }, ['vignette']),
  createMegaEffect('pro-mega-motion-shaky', 'Shaky Handheld', 'Intense handheld camera shake.', Camera,
    { shakeFactor: 8 }, [{ name: 'Shake Factor', key: 'shakeFactor', type: 'number', min: 2, max: 30, step: 1 }],
    (ctx: any, video: any, params: any) => { const dx = (Math.random() - 0.5) * params.shakeFactor; const dy = (Math.random() - 0.5) * params.shakeFactor; ctx.translate(dx, dy); }, ['vignette']),
  createMegaEffect('pro-mega-motion-rise', 'Glide Rise', 'Smooth rising camera translation upward.', Move,
    { speed: 0.6, lift: 15 }, [{ name: 'Glide Speed', key: 'speed', type: 'number', min: 0.1, max: 3, step: 0.1 }, { name: 'Lift Distance', key: 'lift', type: 'number', min: 2, max: 50, step: 2 }],
    (ctx: any, video: any, params: any, time: number) => { const dy = Math.sin(time * params.speed) * params.lift; ctx.translate(0, dy); }, ['vignette']),
  createMegaEffect('pro-mega-motion-orbital', 'Orbital Drift', 'Circular floating sway movement.', RefreshCw,
    { speed: 1, radius: 10 }, [{ name: 'Orbit Speed', key: 'speed', type: 'number', min: 0.1, max: 4, step: 0.1 }, { name: 'Radius', key: 'radius', type: 'number', min: 2, max: 30, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.radius; const dy = Math.cos(time * params.speed) * params.radius; ctx.translate(dx, dy); }, ['vignette']),

  // ── CINEMATIC CATEGORY (15 effects) ──
  createMegaEffect('pro-mega-cine-hollywood', 'Hollywood Teal', 'Teal and orange block-buster grading.', Palette,
    { depth: 1.15 }, [{ name: 'Color Depth', key: 'depth', type: 'number', min: 0.5, max: 2, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `contrast(${params.depth}) saturate(1.1) brightness(1.02)`; }, ['vignette']),
  createMegaEffect('pro-mega-cine-noir', 'Noir Contrast', 'Dramatic black & white high-contrast film.', Eye,
    { contrast: 1.55 }, [{ name: 'Contrast Factor', key: 'contrast', type: 'number', min: 1, max: 2.5, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `grayscale(1) contrast(${params.contrast})`; }, ['vignette']),
  createMegaEffect('pro-mega-cine-warm', 'Retro Cinema Warm', 'Warm retro cinema golden wash.', Film,
    { warmth: 0.32 }, [{ name: 'Warmth', key: 'warmth', type: 'number', min: 0.05, max: 0.9, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.warmth}) saturate(1.2)`; }, ['vignette']),
  createMegaEffect('pro-mega-cine-cozy', 'Warm Cozy Tone', 'Comfortable warm amber tint.', Sun,
    { amberFactor: 0.22 }, [{ name: 'Amber Factor', key: 'amberFactor', type: 'number', min: 0.05, max: 0.7, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.amberFactor}) brightness(1.03)`; }, ['vignette']),
  createMegaEffect('pro-mega-cine-arctic', 'Cool Arctic Blue', 'Chill ice-cool landscape styling cast.', Moon,
    { blueCast: 1.18 }, [{ name: 'Blue Intensity', key: 'blueCast', type: 'number', min: 0.5, max: 2, step: 0.05 }],
    (ctx: any) => { ctx.filter = 'hue-rotate(8deg) saturate(0.96)'; }, ['vignette']),
  createMegaEffect('pro-mega-cine-cyber', 'Cyberpunk Glow Look', 'Neon magenta shadows and blue highlights look.', Sparkles,
    { sat: 1.35 }, [{ name: 'Saturate boost', key: 'sat', type: 'number', min: 0.8, max: 2, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `hue-rotate(-20deg) saturate(${params.sat})`; }, ['vignette']),
  createMegaEffect('pro-mega-cine-forest', 'Moody Forest Green', 'Rich emerald green foliage grading.', Palette,
    { greenBoost: 1.2 }, [{ name: 'Green Boost', key: 'greenBoost', type: 'number', min: 0.5, max: 2, step: 0.05 }],
    (ctx: any) => { ctx.filter = 'hue-rotate(12deg) saturate(1.15)'; }, ['vignette']),
  createMegaEffect('pro-mega-cine-desert', 'Desert Sand Tone', 'Warm sand dusty brown tint.', Sun,
    { sandFactor: 0.4 }, [{ name: 'Sand Tint', key: 'sandFactor', type: 'number', min: 0.1, max: 0.9, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.sandFactor}) contrast(1.12)`; }, ['vignette']),
  createMegaEffect('pro-mega-cine-vintage', 'Vintage LUT Color', 'Stylised aged cinema color curves.', Film,
    { tone: 0.28 }, [{ name: 'LUT Tone', key: 'tone', type: 'number', min: 0.05, max: 0.8, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.tone}) saturate(1.12)`; }, ['vignette']),
  createMegaEffect('pro-mega-cine-drama', 'Sepia Drama Look', 'Aged dark brown sepia wash.', Film,
    { intensity: 0.55 }, [{ name: 'Sepia Intensity', key: 'intensity', type: 'number', min: 0.1, max: 1, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.intensity}) contrast(1.18)`; }, ['vignette']),
  createMegaEffect('pro-mega-cine-log', 'Documentary Flat Log', 'Muted low contrast flat profile log look.', Film,
    { flatFactor: 0.4 }, [{ name: 'Flat Curve', key: 'flatFactor', type: 'number', min: 0.1, max: 0.8, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `brightness(1.06) contrast(${1 - params.flatFactor}) saturate(0.85)`; }, ['vignette']),
  createMegaEffect('pro-mega-cine-pastel', 'Pastel Dream', 'Bright pastel color styling look.', Sparkles,
    { brightness: 1.15, contrast: 0.88 },
    [{ name: 'Brightness', key: 'brightness', type: 'number', min: 0.9, max: 1.4, step: 0.02 }, { name: 'Contrast', key: 'contrast', type: 'number', min: 0.6, max: 1.2, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `brightness(${params.brightness}) contrast(${params.contrast}) saturate(0.92)`; }, ['vignette']),
  createMegaEffect('pro-mega-cine-indie', 'Indie Film Look', 'Stylised warm shadows and faded greens aesthetic.', Clapperboard,
    { warmShadows: 1.12 }, [{ name: 'Warm factor', key: 'warmShadows', type: 'number', min: 0.5, max: 2, step: 0.05 }],
    (ctx: any) => { ctx.filter = 'hue-rotate(4deg) saturate(1.08)'; }, ['vignette']),
  createMegaEffect('pro-mega-cine-silver', 'Silver Classic BW', 'Classic monochrome high-glow style.', Film,
    { contrast: 1.35 }, [{ name: 'Contrast Factor', key: 'contrast', type: 'number', min: 0.8, max: 2, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `grayscale(1) contrast(${params.contrast}) brightness(1.03)`; }, ['vignette']),
  createMegaEffect('pro-mega-cine-emerald', 'Emerald Cine Grade', 'Luxury deep green tones cast.', Palette,
    { emeraldFactor: 1.18 }, [{ name: 'Emerald Intensity', key: 'emeraldFactor', type: 'number', min: 0.5, max: 2, step: 0.05 }],
    (ctx: any) => { ctx.filter = 'hue-rotate(18deg) saturate(1.1)'; }, ['vignette']),

  // ── GLITCH CATEGORY (15 effects) ──
  createMegaEffect('pro-mega-glitch-tear', 'Screen Tear Mega', 'Violent horizontal screen tearing blocks.', EyeOff,
    { tearWidth: 35 }, [{ name: 'Tear Width', key: 'tearWidth', type: 'number', min: 5, max: 100, step: 5 }],
    (ctx: any, video: any, params: any) => { if (Math.random() > 0.8) { ctx.translate((Math.random() - 0.5) * params.tearWidth, 0); } }, ['vignette']),
  createMegaEffect('pro-mega-glitch-block', 'Block Corrupt', 'Random color digital corruption rectangles.', Zap,
    { rate: 0.2, size: 30 },
    [{ name: 'Corrupt Rate', key: 'rate', type: 'number', min: 0.05, max: 0.9, step: 0.05 }, { name: 'Block size', key: 'size', type: 'number', min: 5, max: 80, step: 2 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { if (Math.random() < params.rate) { ctx.fillStyle = 'rgba(255,0,0,0.2)'; ctx.fillRect(Math.random() * canvas.width, Math.random() * canvas.height, params.size * 2, params.size); } }, ['vignette']),
  createMegaEffect('pro-mega-glitch-chrom', 'Chromatic Offset', 'Strobing chromatic aberration splits.', Sliders,
    { shift: 10 }, [{ name: 'RGB Shift', key: 'shift', type: 'number', min: 2, max: 30, step: 1 }],
    (ctx: any) => { ctx.filter = 'saturate(1.08)'; }, ['vignette']),
  createMegaEffect('pro-mega-glitch-invert', 'Inversion Flash', 'Rapid inversion strobe flashes.', ShieldAlert,
    { frequency: 3 }, [{ name: 'Strobe speed', key: 'frequency', type: 'number', min: 0.5, max: 8, step: 0.5 }],
    (ctx: any, video: any, params: any, time: number) => { if ((time * params.frequency) % 1 < 0.12) { ctx.filter = 'invert(1)'; } }, ['negate']),
  createMegaEffect('pro-mega-glitch-loss', 'Signal Loss Mega', 'Heavy analogue video signal sync rolls.', Radio,
    { rollSpeed: 1.2 }, [{ name: 'Sync Roll Speed', key: 'rollSpeed', type: 'number', min: 0.1, max: 4, step: 0.1 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { const dy = (time * params.rollSpeed * 80) % canvas.height; ctx.translate(0, dy * 0.1); }, ['crop=iw:ih-20:0:10']),
  createMegaEffect('pro-mega-glitch-cable', 'Bad Cable TV', 'Horizontal white noise static line bar overlays.', Tv,
    { intensity: 0.35 }, [{ name: 'Noise Intensity', key: 'intensity', type: 'number', min: 0.05, max: 0.9, step: 0.05 }],
    (ctx: any) => { ctx.filter = 'contrast(1.08)'; }, ['vignette']),
  createMegaEffect('pro-mega-glitch-strobe', 'Strobe Rainbow', 'Rapid colorful strobe flashes.', Zap,
    { speed: 6 }, [{ name: 'Strobe Speed', key: 'speed', type: 'number', min: 1, max: 15, step: 0.5 }],
    (ctx: any, video: any, params: any, time: number) => { if (Math.sin(time * params.speed * 3) > 0.6) { ctx.filter = `hue-rotate(${time * 120}deg) saturate(1.2)`; } }, ['vignette']),
  createMegaEffect('pro-mega-glitch-data', 'Data Noise Buzz', 'Random high-frequency frame tracking buzz offsets.', Radio,
    { buzz: 10 }, [{ name: 'Buzz Range', key: 'buzz', type: 'number', min: 2, max: 40, step: 1 }],
    (ctx: any, video: any, params: any) => { if (Math.random() < 0.3) { ctx.translate((Math.random() - 0.5) * params.buzz, 0); } }, ['vignette']),
  createMegaEffect('pro-mega-glitch-scan', 'Scanline Jitter Mega', 'Fine scanline alignment jitter twitching.', EyeOff,
    { jitter: 15 }, [{ name: 'Jitter Offset', key: 'jitter', type: 'number', min: 2, max: 40, step: 1 }],
    (ctx: any, video: any, params: any) => { ctx.translate((Math.random() - 0.5) * params.jitter, 0); }, ['crop=iw-20:ih:10:0']),
  createMegaEffect('pro-mega-glitch-corrupt', 'Pixel Corrupt Mega', 'Blocky digital compression block corruption.', Zap,
    { corruption: 14 }, [{ name: 'Corruption factor', key: 'corruption', type: 'number', min: 2, max: 50, step: 1 }],
    (ctx: any) => { ctx.filter = 'contrast(1.1)'; }, ['vignette']),
  createMegaEffect('pro-mega-glitch-broken', 'Broken LCD Mega', 'Horizontal LCD horizontal and vertical line crack overlays.', Tv,
    { crackDensity: 6 }, [{ name: 'Crack Density', key: 'crackDensity', type: 'number', min: 1, max: 20, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(0.98)'; }, ['vignette']),
  createMegaEffect('pro-mega-glitch-wave', 'Wave Jitter Mega', 'Continuous horizontal wave jitter sweeps.', Zap,
    { amplitude: 12 }, [{ name: 'Wave Amplitude', key: 'amplitude', type: 'number', min: 2, max: 40, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * 6) * params.amplitude; ctx.translate(dx, 0); }, ['crop=iw-20:ih:10:0']),
  createMegaEffect('pro-mega-glitch-buzz', 'VHS Tape Buzz', 'VHS head grain static tracked lines.', Tv,
    { lines: 4 }, [{ name: 'Tracking lines', key: 'lines', type: 'number', min: 1, max: 12, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.02)'; }, ['vignette']),
  createMegaEffect('pro-mega-glitch-phase', 'Phase Shift Mega', 'Analogue phase shift offset displacement.', Zap,
    { displacement: 16 }, [{ name: 'Phase Offset', key: 'displacement', type: 'number', min: 2, max: 50, step: 1 }],
    (ctx: any) => { ctx.filter = 'saturate(1.05)'; }, ['vignette']),
  createMegaEffect('pro-mega-glitch-holog', 'Corrupted Hologram', 'Glowing cyan scanlines with intermittent flicker.', Terminal,
    { opacity: 0.35 }, [{ name: 'Flicker opacity', key: 'opacity', type: 'number', min: 0.05, max: 0.9, step: 0.05 }],
    (ctx: any, video: any, params: any, time: number) => { if (Math.sin(time * 12) > 0.4) { ctx.fillStyle = `rgba(0,255,255, ${params.opacity * 0.25})`; ctx.fillRect(0,0,9999,9999); } }, ['vignette']),

  // ── CAMERA CATEGORY (15 effects) ──
  createMegaEffect('pro-mega-cam-pan', 'Pan L to R Mega', 'Continuous automated horizontal panning.', Move,
    { speed: 0.6, range: 30 }, [{ name: 'Pan Speed', key: 'speed', type: 'number', min: 0.1, max: 3, step: 0.1 }, { name: 'Drift Range', key: 'range', type: 'number', min: 5, max: 100, step: 5 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.range; ctx.translate(dx, 0); }, ['crop=iw-50:ih:25:0']),
  createMegaEffect('pro-mega-cam-tilt', 'Tilt U to D Mega', 'Continuous automated vertical camera tilting.', Move,
    { speed: 0.6, range: 25 }, [{ name: 'Tilt Speed', key: 'speed', type: 'number', min: 0.1, max: 3, step: 0.1 }, { name: 'Tilt Range', key: 'range', type: 'number', min: 5, max: 80, step: 5 }],
    (ctx: any, video: any, params: any, time: number) => { const dy = Math.cos(time * params.speed) * params.range; ctx.translate(0, dy); }, ['crop=iw:ih-40:0:20']),
  createMegaEffect('pro-mega-cam-diag', 'Diagonal Sweep', 'Sweeping diagonal camera motion.', Move,
    { speed: 0.8, offset: 24 }, [{ name: 'Sweep Speed', key: 'speed', type: 'number', min: 0.1, max: 3, step: 0.1 }, { name: 'Sweep Offset', key: 'offset', type: 'number', min: 5, max: 100, step: 5 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.offset; const dy = Math.cos(time * params.speed) * params.offset; ctx.translate(dx, dy); }, ['crop=iw-44:ih-44:22:22']),
  createMegaEffect('pro-mega-cam-orbit', 'Orbit Tilt Cam', 'Orbital rotation camera tilt.', RefreshCw,
    { speed: 1.2, angle: 0.08 }, [{ name: 'Orbit Speed', key: 'speed', type: 'number', min: 0.1, max: 4, step: 0.1 }, { name: 'Tilt Angle', key: 'angle', type: 'number', min: 0.01, max: 0.4, step: 0.01 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { ctx.translate(canvas.width / 2, canvas.height / 2); ctx.rotate(Math.sin(time * params.speed) * params.angle); ctx.translate(-canvas.width / 2, -canvas.height / 2); }, ['rotate=0.04']),
  createMegaEffect('pro-mega-cam-dolly', 'Dolly Zoom Mega', 'Dynamic dolly zoom simulation.', ZoomIn,
    { speed: 0.8, maxZoom: 1.35 }, [{ name: 'Speed', key: 'speed', type: 'number', min: 0.1, max: 3, step: 0.1 }, { name: 'Zoom Limit', key: 'maxZoom', type: 'number', min: 1.05, max: 2.2, step: 0.05 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { const currentZoom = 1 + (time * params.speed) % (params.maxZoom - 1); ctx.translate(canvas.width / 2, canvas.height / 2); ctx.scale(currentZoom, currentZoom); ctx.translate(-canvas.width / 2, -canvas.height / 2); }, ['scale=iw*1.15:ih*1.15,crop=iw/1.15:ih/1.15']),
  createMegaEffect('pro-mega-cam-matrix', 'Matrix Warp Cam', 'Diagonal matrix distortion sway.', Camera,
    { angle: 0.06 }, [{ name: 'Tilt Factor', key: 'angle', type: 'number', min: 0.01, max: 0.3, step: 0.01 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { ctx.translate(canvas.width / 2, canvas.height / 2); ctx.rotate(params.angle); ctx.translate(-canvas.width / 2, -canvas.height / 2); }, ['rotate=0.03']),
  createMegaEffect('pro-mega-cam-hyper', 'Hyperlapse Shift Mega', 'Step frame time adjustments hyperlapse.', RefreshCw,
    { speed: 2, shiftSteps: 8 }, [{ name: 'Lapse Speed', key: 'speed', type: 'number', min: 0.5, max: 6, step: 0.1 }, { name: 'Lapse Steps', key: 'shiftSteps', type: 'number', min: 2, max: 20, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const step = Math.floor(time * params.speed) % params.shiftSteps; ctx.translate(step * 2.5, 0); }, ['crop=iw-10:ih:5:0']),
  createMegaEffect('pro-mega-cam-steady', 'Steadicam Float', 'Floaty stabilised camera movement.', Eye,
    { speed: 1.4, damping: 4.5 }, [{ name: 'Speed', key: 'speed', type: 'number', min: 0.1, max: 4, step: 0.1 }, { name: 'Dampening', key: 'damping', type: 'number', min: 1, max: 20, step: 0.5 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.damping; ctx.translate(dx, 0); }, ['crop=iw-12:ih:6:0']),
  createMegaEffect('pro-mega-cam-drone', 'Drone Pass Pan', 'High altitude pan camera glide.', Camera,
    { speed: 0.7, panFactor: 22 }, [{ name: 'Flight Speed', key: 'speed', type: 'number', min: 0.1, max: 2, step: 0.1 }, { name: 'Flight Drift', key: 'panFactor', type: 'number', min: 5, max: 80, step: 5 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { const dx = (time * params.speed * params.panFactor) % canvas.width; ctx.translate(-dx * 0.1, 0); }, ['crop=iw-20:ih:10:0']),
  createMegaEffect('pro-mega-cam-handheld', 'Handheld Shake Mega', 'Erratic dynamic human handheld holding simulation.', Shuffle,
    { speed: 2.5, force: 6 }, [{ name: 'Frequency', key: 'speed', type: 'number', min: 0.5, max: 5, step: 0.1 }, { name: 'Shake Force', key: 'force', type: 'number', min: 1, max: 20, step: 0.5 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.force; const dy = Math.cos(time * params.speed * 0.8) * params.force; ctx.translate(dx, dy); }, ['crop=iw-10:ih-10:5:5']),
  createMegaEffect('pro-mega-cam-shake', 'Shake Quick Zoom', 'Vibrating action quick camera zoom.', ZoomIn,
    { speed: 6, zoom: 1.15 }, [{ name: 'Shake Frequency', key: 'speed', type: 'number', min: 1, max: 15, step: 0.5 }, { name: 'Zoom Factor', key: 'zoom', type: 'number', min: 1, max: 1.5, step: 0.02 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { const scale = 1 + Math.abs(Math.sin(time * params.speed)) * (params.zoom - 1); ctx.translate(canvas.width/2, canvas.height/2); ctx.scale(scale, scale); ctx.translate(-canvas.width/2, -canvas.height/2); }, ['scale=iw*1.15:ih*1.15,crop=iw/1.15:ih/1.15']),
  createMegaEffect('pro-mega-cam-float', 'Smooth Float Cam', 'Slow floaty vertical camera panning.', Move,
    { speed: 0.5, height: 18 }, [{ name: 'Float Speed', key: 'speed', type: 'number', min: 0.1, max: 2, step: 0.1 }, { name: 'Float Height', key: 'height', type: 'number', min: 2, max: 50, step: 2 }],
    (ctx: any, video: any, params: any, time: number) => { const dy = Math.sin(time * params.speed) * params.height; ctx.translate(0, dy); }, ['crop=iw:ih-36:0:18']),
  createMegaEffect('pro-mega-cam-quickwhip', 'Quick Whip Pan Mega', 'Aggressive warp quick whip pan.', Move,
    { speed: 5, force: 50 }, [{ name: 'Whip Speed', key: 'speed', type: 'number', min: 1, max: 10, step: 0.5 }, { name: 'Whip Force', key: 'force', type: 'number', min: 10, max: 150, step: 5 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.force; ctx.translate(dx, 0); }, ['crop=iw-100:ih:50:0']),
  createMegaEffect('pro-mega-cam-crane', 'Crane Pan Shot', 'Horizontal crane sweeping pan tilt.', Move,
    { liftSpeed: 0.9, liftFactor: 20 }, [{ name: 'Crane Speed', key: 'liftSpeed', type: 'number', min: 0.1, max: 3, step: 0.1 }, { name: 'Crane Lift', key: 'liftFactor', type: 'number', min: 5, max: 60, step: 2 }],
    (ctx: any, video: any, params: any, time: number) => { const dy = Math.sin(time * params.liftSpeed) * params.liftFactor; ctx.translate(0, dy); }, ['crop=iw:ih-30:0:15']),
  createMegaEffect('pro-mega-cam-slowdolly', 'Slow Dolly Mega', 'Ultra slow horizontal dolly translation.', Move,
    { speed: 0.12, offsetRange: 35 }, [{ name: 'Dolly Speed', key: 'speed', type: 'number', min: 0.05, max: 1, step: 0.05 }, { name: 'Offset Range', key: 'offsetRange', type: 'number', min: 5, max: 100, step: 5 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.offsetRange; ctx.translate(dx, 0); }, ['crop=iw-50:ih:25:0']),

  // ── DISTORTION CATEGORY (10 effects) ──
  createMegaEffect('pro-mega-dist-vert', 'Vertical Waves Mega', 'Wavy vertical line coordinate waves.', RefreshCw,
    { frequency: 3, amplitude: 14 }, [{ name: 'Frequency', key: 'frequency', type: 'number', min: 0.5, max: 8, step: 0.1 }, { name: 'Amplitude', key: 'amplitude', type: 'number', min: 2, max: 40, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.frequency) * params.amplitude; ctx.translate(dx, 0); }, ['crop=iw-20:ih:10:0']),
  createMegaEffect('pro-mega-dist-vortex', 'Vortex Warp Mega', 'Centred swirling spiral vortex.', RefreshCw,
    { speed: 1.8, angle: 0.15 }, [{ name: 'Vortex Speed', key: 'speed', type: 'number', min: 0.1, max: 5, step: 0.1 }, { name: 'Vortex Angle', key: 'angle', type: 'number', min: 0.01, max: 0.5, step: 0.01 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { ctx.translate(canvas.width / 2, canvas.height / 2); ctx.rotate(Math.sin(time * params.speed) * params.angle); ctx.translate(-canvas.width / 2, -canvas.height / 2); }, ['rotate=0.05']),
  createMegaEffect('pro-mega-dist-magnify', 'Magnify Glass Mega', 'Centre circular focal magnifying glass warp.', ZoomIn,
    { zoom: 1.45 }, [{ name: 'Zoom factor', key: 'zoom', type: 'number', min: 1, max: 3, step: 0.05 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { ctx.translate(canvas.width / 2, canvas.height / 2); ctx.scale(params.zoom, params.zoom); ctx.translate(-canvas.width / 2, -canvas.height / 2); }, ['scale=iw*1.2:ih*1.2,crop=iw/1.2:ih/1.2']),
  createMegaEffect('pro-mega-dist-melt', 'Pixel Melt Mega', 'Dissolves canvas lines downwards.', Shuffle,
    { speed: 2.2, scale: 20 }, [{ name: 'Melt Speed', key: 'speed', type: 'number', min: 0.5, max: 5, step: 0.1 }, { name: 'Melt Scale', key: 'scale', type: 'number', min: 2, max: 40, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const dy = Math.sin(time * params.speed) * params.scale; ctx.translate(0, dy); }, ['crop=iw:ih-20:0:10']),
  createMegaEffect('pro-mega-dist-shear', 'Shear Warp Mega', 'Diagonal geometry shear distortion.', HelpCircle,
    { factor: 0.12 }, [{ name: 'Shear Force', key: 'factor', type: 'number', min: 0.01, max: 0.5, step: 0.01 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { ctx.translate(canvas.width / 2, canvas.height / 2); ctx.rotate(params.factor); ctx.translate(-canvas.width / 2, -canvas.height / 2); }, ['rotate=0.03']),
  createMegaEffect('pro-mega-dist-zigzag', 'Zigzag Warp Mega', 'Zigzag wave alignment jitter.', Shuffle,
    { peaks: 5, amplitude: 12 }, [{ name: 'Zigzag Peaks', key: 'peaks', type: 'number', min: 1, max: 12, step: 1 }, { name: 'Amplitude', key: 'amplitude', type: 'number', min: 2, max: 40, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * 3) * params.amplitude; ctx.translate(dx, 0); }, ['crop=iw-24:ih:12:0']),
  createMegaEffect('pro-mega-dist-mirror', 'Fun Mirror Mega', 'Splits canvas vertically mirroring left side.', HelpCircle,
    { bend: 0.06 }, [{ name: 'Bend Factor', key: 'bend', type: 'number', min: 0.01, max: 0.3, step: 0.01 }],
    (ctx: any) => { ctx.filter = 'brightness(1.02)'; }, ['vignette']),
  createMegaEffect('pro-mega-dist-kaleido4', '4-Way Kaleido Mega', '4-way mirrored quadrant kaleidoscope.', Eye,
    { scale: 1 }, [{ name: 'Mirror Scale', key: 'scale', type: 'number', min: 0.5, max: 1.5, step: 0.1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.01)'; }, ['vignette']),
  createMegaEffect('pro-mega-dist-kaleido8', '8-Way Kaleido Mega', '8-way mirrored octagonal kaleidoscope.', Eye,
    { scale: 1 }, [{ name: 'Mirror Scale', key: 'scale', type: 'number', min: 0.5, max: 1.5, step: 0.1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.01)'; }, ['vignette']),
  createMegaEffect('pro-mega-dist-skew', 'Skew Perspective Mega', 'Perspective skew angle coordinate warp.', Compass,
    { skewX: 0.1, skewY: 0.07 }, [{ name: 'Skew X', key: 'skewX', type: 'number', min: 0, max: 0.4, step: 0.01 }, { name: 'Skew Y', key: 'skewY', type: 'number', min: 0, max: 0.4, step: 0.01 }],
    (ctx: any, video: any, params: any) => { ctx.transform(1, params.skewY, params.skewX, 1, 0, 0); }, ['rotate=0.03'])
];
