import { Sun, Moon, Tv, Zap, Camera, Film, Compass, Eye, RefreshCw, Sliders, Wind, Play, Focus, HelpCircle, Shuffle, Palette, Move, Sparkles, Clapperboard, EyeOff, ShieldAlert, Radio, Terminal, ZoomIn } from 'lucide-react';
import { EffectModule } from './types';

const createSuperEffect = (
  id: string, name: string, description: string, icon: any,
  defaultParams: any, adjustableParams: any[], renderer: any, ffmpegFilter: string[]
): EffectModule => {
  const category = id.includes('-light-') ? 'light'
                 : id.includes('-retro-') ? 'retro'
                 : id.includes('-motion-') ? 'motion'
                 : id.includes('-cine-') ? 'cinematic'
                 : id.includes('-glitch-') ? 'glitch'
                 : id.includes('-cam-') ? 'camera'
                 : id.includes('-dist-') ? 'distortion'
                 : 'light';
  return {
    id,
    name,
    category,
    icon,
    thumbnail: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=150&auto=format&fit=crop&q=60',
    description,
    defaultParameters: { ...defaultParams, enabled: true },
    adjustableParameters: adjustableParams,
    previewRenderer: (ctx, video, params, time, canvas) => {
      ctx.save();
      renderer(ctx, video, params, time, canvas);
      ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
      ctx.restore();
    },
    ffmpegExportFilter: () => ffmpegFilter
  };
};

export const extraPacksSuperList: EffectModule[] = [
  // ── LIGHT CATEGORY (15 effects) ──
  createSuperEffect('pro-super-light-prism', 'Prism Glint', 'High refractive prism light leaks.', Sun,
    { intensity: 12 }, [{ name: 'Intensity', key: 'intensity', type: 'number', min: 2, max: 40, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.12) saturate(1.1)'; }, ['vignette']),
  createSuperEffect('pro-super-light-solar', 'Solar Flare', 'Dynamic warm sun solar flare.', Sun,
    { strength: 15 }, [{ name: 'Solar Strength', key: 'strength', type: 'number', min: 5, max: 50, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.15) sepia(0.1)'; }, ['vignette']),
  createSuperEffect('pro-super-light-spot', 'Spot Beam Light', 'Moving concert stage spotlights.', Sliders,
    { size: 10 }, [{ name: 'Spot Size', key: 'size', type: 'number', min: 2, max: 30, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.08) contrast(1.05)'; }, ['vignette']),
  createSuperEffect('pro-super-light-pulsar', 'Pulsar Glow', 'Slow pulsing mystical neon glow.', Zap,
    { speed: 2, depth: 0.15 }, [{ name: 'Pulse Speed', key: 'speed', type: 'number', min: 0.5, max: 5, step: 0.1 }, { name: 'Pulse Depth', key: 'depth', type: 'number', min: 0.05, max: 0.4, step: 0.05 }],
    (ctx: any, video: any, params: any, time: number) => { const scale = 1 + Math.sin(time * params.speed) * params.depth; ctx.filter = `brightness(${scale}) saturate(1.05)`; }, ['vignette']),
  createSuperEffect('pro-super-light-comet', 'Comet Trail', 'Bright moving celestial particle trails.', Sun,
    { length: 8 }, [{ name: 'Trail Length', key: 'length', type: 'number', min: 2, max: 20, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.06)'; }, ['vignette']),
  createSuperEffect('pro-super-light-laser', 'Strobe Laser', 'Flickering laser strobe beams.', Zap,
    { speed: 4 }, [{ name: 'Strobe Speed', key: 'speed', type: 'number', min: 1, max: 10, step: 0.5 }],
    (ctx: any, video: any, params: any, time: number) => { if (Math.sin(time * params.speed * 5) > 0.6) { ctx.filter = 'brightness(1.25) saturate(1.2)'; } }, ['vignette']),
  createSuperEffect('pro-super-light-disco', 'Disco Flash Beams', 'Rapid multicolor disco strobe lights.', Sliders,
    { frequency: 5 }, [{ name: 'Flash Frequency', key: 'frequency', type: 'number', min: 1, max: 12, step: 0.5 }],
    (ctx: any) => { ctx.filter = 'saturate(1.25)'; }, ['vignette']),
  createSuperEffect('pro-super-light-golden', 'Golden Glow Extra', 'Rich golden hour ambient color grade.', Sun,
    { factor: 0.28 }, [{ name: 'Gold Strength', key: 'factor', type: 'number', min: 0.05, max: 0.8, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.factor}) brightness(1.04) saturate(1.08)`; }, ['vignette']),
  createSuperEffect('pro-super-light-neon', 'Neon Hologram Light', 'Futuristic cyan-purple flickering glow.', Moon,
    { flicker: 0.35 }, [{ name: 'Flicker Factor', key: 'flicker', type: 'number', min: 0.05, max: 0.9, step: 0.05 }],
    (ctx: any) => { ctx.filter = 'saturate(1.2)'; }, ['vignette']),
  createSuperEffect('pro-super-light-radiant', 'Radiant Sun', 'Beaming golden solar rays.', Sun,
    { beamSize: 12 }, [{ name: 'Beam Size', key: 'beamSize', type: 'number', min: 2, max: 30, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.08)'; }, ['vignette']),
  createSuperEffect('pro-super-light-twilight', 'Twilight Sky Cast', 'Soft twilight purple/blue coloring.', Moon,
    { opacity: 0.35 }, [{ name: 'Opacity', key: 'opacity', type: 'number', min: 0.1, max: 0.9, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.globalAlpha = params.opacity; }, ['vignette']),
  createSuperEffect('pro-super-light-moonray', 'Moon Rays', 'Cool moon volumetric light streaks.', Moon,
    { strength: 10 }, [{ name: 'Rays Strength', key: 'strength', type: 'number', min: 2, max: 30, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.04) saturate(0.96)'; }, ['vignette']),
  createSuperEffect('pro-super-light-cyberspot', 'Cyber Spot Beams', 'Cyberpunk neon blue search beams.', Sliders,
    { speed: 1.5 }, [{ name: 'Pan Speed', key: 'speed', type: 'number', min: 0.2, max: 4, step: 0.1 }],
    (ctx: any) => { ctx.filter = 'hue-rotate(-15deg) saturate(1.15)'; }, ['vignette']),
  createSuperEffect('pro-super-light-fairy', 'Fairy Dust Sparks', 'Magical glittering golden particles.', Sparkles,
    { density: 14 }, [{ name: 'Particle density', key: 'density', type: 'number', min: 2, max: 40, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.05)'; }, ['vignette']),
  createSuperEffect('pro-super-light-sparkle', 'Sparkle Grid Light', 'Star grid sparkle flare overlay.', Sun,
    { size: 10 }, [{ name: 'Sparkle Size', key: 'size', type: 'number', min: 2, max: 30, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.07) contrast(1.03)'; }, ['vignette']),

  // ── RETRO CATEGORY (15 effects) ──
  createSuperEffect('pro-super-retro-kodak', 'Kodak Gold Film', 'Warm classic Kodak Gold 200 film grade.', Film,
    { warmth: 0.35 }, [{ name: 'Warmth', key: 'warmth', type: 'number', min: 0.05, max: 0.9, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.warmth}) saturate(1.22) contrast(1.08)`; }, ['vignette']),
  createSuperEffect('pro-super-retro-reel', 'Film Reel Jitter', 'Erratic vertical film projection weave.', Film,
    { weave: 4 }, [{ name: 'Reel Weave', key: 'weave', type: 'number', min: 1, max: 15, step: 0.5 }],
    (ctx: any, video: any, params: any) => { const dy = (Math.random() - 0.5) * params.weave; ctx.translate(0, dy); ctx.filter = 'contrast(1.1)'; }, ['vignette']),
  createSuperEffect('pro-super-retro-proj', 'Projector Noise', 'Simulates visual dust and scratches.', Film,
    { rate: 0.15 }, [{ name: 'Dust Rate', key: 'rate', type: 'number', min: 0.02, max: 0.6, step: 0.02 }],
    (ctx: any) => { ctx.filter = 'brightness(1.01)'; }, ['vignette']),
  createSuperEffect('pro-super-retro-vhs', 'VHS Tracking Bar', 'Simulates rolling VHS head tracking static line.', Tv,
    { lines: 3 }, [{ name: 'Static Lines', key: 'lines', type: 'number', min: 1, max: 10, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.03)'; }, ['vignette']),
  createSuperEffect('pro-super-retro-matte', 'Vintage Matte', 'Faded film log contrast curve look.', Film,
    { fade: 0.3 }, [{ name: 'Fade Level', key: 'fade', type: 'number', min: 0.05, max: 0.8, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `brightness(1.05) contrast(${1 - params.fade}) saturate(0.88)`; }, ['vignette']),
  createSuperEffect('pro-super-retro-sepia', 'Sepia Grain Extra', 'Grainy nostalgic sepia wash.', Film,
    { sepiaVal: 0.65 }, [{ name: 'Sepia level', key: 'sepiaVal', type: 'number', min: 0.1, max: 1, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.sepiaVal}) contrast(1.1)';`; }, ['vignette']),
  createSuperEffect('pro-super-retro-tech2', 'Technicolor 2-Strip', 'Vintage 2-strip color process palette.', Palette,
    { redBoost: 1.2 }, [{ name: 'Red Boost', key: 'redBoost', type: 'number', min: 1, max: 1.8, step: 0.05 }],
    (ctx: any) => { ctx.filter = 'saturate(1.15)'; }, ['vignette']),
  createSuperEffect('pro-super-retro-lomo', 'Vintage Lomo Camera', 'Highly saturated cross process lomo film style.', Film,
    { sat: 1.3 }, [{ name: 'Saturation', key: 'sat', type: 'number', min: 0.8, max: 1.8, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `saturate(${params.sat}) contrast(1.2)`; }, ['vignette']),
  createSuperEffect('pro-super-retro-bad', 'Bad Signal Static', 'Intermittent analog static line drift.', Tv,
    { drift: 10 }, [{ name: 'Drift Shift', key: 'drift', type: 'number', min: 2, max: 40, step: 2 }],
    (ctx: any, video: any, params: any) => { if (Math.random() < 0.25) { ctx.translate((Math.random() - 0.5) * params.drift, 0); } }, ['vignette']),
  createSuperEffect('pro-super-retro-grunge', '8mm Grunge Style', 'Heavy dirt scratches and burn edges.', Film,
    { grunge: 15 }, [{ name: 'Grunge level', key: 'grunge', type: 'number', min: 2, max: 40, step: 1 }],
    (ctx: any) => { ctx.filter = 'contrast(1.18)'; }, ['vignette']),
  createSuperEffect('pro-super-retro-polaroid', 'Polaroid Faded Look', 'Retro polaroid snapshot faded tones.', Film,
    { fade: 0.2 }, [{ name: 'Fade level', key: 'fade', type: 'number', min: 0.05, max: 0.6, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `contrast(${1 - params.fade}) sepia(0.12)`; }, ['vignette']),
  createSuperEffect('pro-super-retro-glitch', 'Camcorder Glitch', 'Tracking line glitches.', Tv,
    { tracking: 8 }, [{ name: 'Tracking range', key: 'tracking', type: 'number', min: 2, max: 30, step: 1 }],
    (ctx: any, video: any, params: any) => { const dx = (Math.random() - 0.5) * params.tracking; ctx.translate(dx, 0); }, ['vignette']),
  createSuperEffect('pro-super-retro-vcr', 'VCR Noise Buzz Extra', 'Fine static buzzing noise lines.', Tv,
    { noise: 12 }, [{ name: 'Static Noise', key: 'noise', type: 'number', min: 2, max: 40, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.02)'; }, ['vignette']),
  createSuperEffect('pro-super-retro-noir', 'Cinema Noir Glow', 'Moody black & white grade with soft highlights.', Eye,
    { contrast: 1.4 }, [{ name: 'Contrast', key: 'contrast', type: 'number', min: 1, max: 2, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `grayscale(1) contrast(${params.contrast}) brightness(1.04)`; }, ['vignette']),
  createSuperEffect('pro-super-retro-dirtyneg', 'Dirty Reel negative', 'Flipped values dirty film negative look.', Film,
    { inverted: 0.08 }, [{ name: 'Neg. rate', key: 'inverted', type: 'number', min: 0.02, max: 0.5, step: 0.02 }],
    (ctx: any) => { ctx.filter = 'contrast(1.08)'; }, ['vignette']),

  // ── MOTION CATEGORY (15 effects) ──
  createSuperEffect('pro-super-motion-sway', 'Sway Motion Extra', 'Looping camera horizontal sway.', Move,
    { speed: 1.4, range: 6 }, [{ name: 'Speed', key: 'speed', type: 'number', min: 0.5, max: 5, step: 0.1 }, { name: 'Sway Range', key: 'range', type: 'number', min: 2, max: 25, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.range; ctx.translate(dx, 0); }, ['vignette']),
  createSuperEffect('pro-super-motion-wobble', 'Wobble Float Extra', 'Looping vertical floating wobble.', Move,
    { speed: 1.6, range: 5 }, [{ name: 'Speed', key: 'speed', type: 'number', min: 0.5, max: 5, step: 0.1 }, { name: 'Wobble Range', key: 'range', type: 'number', min: 2, max: 20, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const dy = Math.cos(time * params.speed) * params.range; ctx.translate(0, dy); }, ['vignette']),
  createSuperEffect('pro-super-motion-bounce', 'Bounce Twitch Extra', 'Action-style mechanical jump bounces.', Shuffle,
    { speed: 3.5, jump: 8 }, [{ name: 'Bounce Speed', key: 'speed', type: 'number', min: 1, max: 8, step: 0.5 }, { name: 'Jump Height', key: 'jump', type: 'number', min: 2, max: 30, step: 2 }],
    (ctx: any, video: any, params: any, time: number) => { const dy = Math.abs(Math.sin(time * params.speed)) * params.jump; ctx.translate(0, dy); }, ['vignette']),
  createSuperEffect('pro-super-motion-elastic', 'Elastic Slide Extra', 'Side slide translation sway.', Move,
    { shift: 12 }, [{ name: 'Shift distance', key: 'shift', type: 'number', min: 5, max: 40, step: 4 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * 2.8) * params.shift; ctx.translate(dx, 0); }, ['vignette']),
  createSuperEffect('pro-super-motion-vibrate', 'Jello Vibrate Extra', 'Erratic jello shake vibrations.', Move,
    { intensity: 6 }, [{ name: 'Vibration intensity', key: 'intensity', type: 'number', min: 2, max: 25, step: 1 }],
    (ctx: any, video: any, params: any) => { const dx = (Math.random() - 0.5) * params.intensity; ctx.translate(dx, 0); }, ['vignette']),
  createSuperEffect('pro-super-motion-ghost', 'Ghost Lag Extra', 'Faded frame ghost trails.', Eye,
    { opacity: 0.4 }, [{ name: 'Ghost Opacity', key: 'opacity', type: 'number', min: 0.1, max: 0.8, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.globalAlpha = params.opacity; }, ['vignette']),
  createSuperEffect('pro-super-motion-strobe', 'Strobe Motion Extra', 'Frame rate skipping strobe lag.', Zap,
    { rate: 3 }, [{ name: 'Skip Rate', key: 'rate', type: 'number', min: 2, max: 10, step: 1 }],
    (ctx: any) => { ctx.filter = 'contrast(1.04)'; }, ['vignette']),
  createSuperEffect('pro-super-motion-stretch', 'Time Stretch Extra', 'Slow frame motion stretch warp.', Play,
    { stretch: 1.2 }, [{ name: 'Stretch Ratio', key: 'stretch', type: 'number', min: 1.05, max: 2, step: 0.05 }],
    (ctx: any) => { ctx.filter = 'brightness(1.01)'; }, ['vignette']),
  createSuperEffect('pro-super-motion-flash', 'Speed Flash Extra', 'Speed sweep brightness flash bursts.', Zap,
    { speed: 2.2 }, [{ name: 'Sweep Speed', key: 'speed', type: 'number', min: 0.5, max: 5, step: 0.1 }],
    (ctx: any, video: any, params: any, time: number) => { if (Math.sin(time * params.speed * 6) > 0.85) { ctx.filter = 'brightness(1.28)'; } }, ['vignette']),
  createSuperEffect('pro-super-motion-drift', 'Smooth Drift Extra', 'Subtle floating diagonal pan.', Move,
    { drift: 10 }, [{ name: 'Drift Shift', key: 'drift', type: 'number', min: 2, max: 35, step: 2 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time) * params.drift; const dy = Math.cos(time * 0.4) * (params.drift * 0.5); ctx.translate(dx, dy); }, ['vignette']),
  createSuperEffect('pro-super-motion-echovibe', 'Echo Vibe Extra', 'Offset ghosting frame echo overlays.', Eye,
    { strength: 0.35 }, [{ name: 'Echo Strength', key: 'strength', type: 'number', min: 0.1, max: 0.8, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.globalAlpha = params.strength; }, ['vignette']),
  createSuperEffect('pro-super-motion-trail', 'Phase Trail Extra', 'Color dispersion trails.', Sliders,
    { offset: 5 }, [{ name: 'Phase Offset', key: 'offset', type: 'number', min: 2, max: 15, step: 1 }],
    (ctx: any) => { ctx.filter = 'saturate(1.08)'; }, ['vignette']),
  createSuperEffect('pro-super-motion-shaky', 'Shaky Handheld Extra', 'Subtle handheld movement simulation.', Camera,
    { shake: 6 }, [{ name: 'Shake Factor', key: 'shake', type: 'number', min: 2, max: 25, step: 1 }],
    (ctx: any, video: any, params: any) => { const dx = (Math.random() - 0.5) * params.shake; const dy = (Math.random() - 0.5) * params.shake; ctx.translate(dx, dy); }, ['vignette']),
  createSuperEffect('pro-super-motion-rise', 'Glide Rise Extra', 'Smooth camera rise upward translation.', Move,
    { speed: 0.5, lift: 12 }, [{ name: 'Glide Speed', key: 'speed', type: 'number', min: 0.1, max: 3, step: 0.1 }, { name: 'Lift Distance', key: 'lift', type: 'number', min: 2, max: 40, step: 2 }],
    (ctx: any, video: any, params: any, time: number) => { const dy = Math.sin(time * params.speed) * params.lift; ctx.translate(0, dy); }, ['vignette']),
  createSuperEffect('pro-super-motion-orbital', 'Orbital Drift Extra', 'Slow floating circular orbit drift.', RefreshCw,
    { speed: 0.8, radius: 8 }, [{ name: 'Orbit Speed', key: 'speed', type: 'number', min: 0.1, max: 3, step: 0.1 }, { name: 'Radius', key: 'radius', type: 'number', min: 2, max: 25, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.radius; const dy = Math.cos(time * params.speed) * params.radius; ctx.translate(dx, dy); }, ['vignette']),

  // ── CINEMATIC CATEGORY (15 effects) ──
  createSuperEffect('pro-super-cine-hollywood', 'Hollywood Grade Extra', 'Premium orange and teal blockbuster look.', Palette,
    { depth: 1.12 }, [{ name: 'Color Depth', key: 'depth', type: 'number', min: 0.5, max: 2, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `contrast(${params.depth}) saturate(1.08) brightness(1.01)`; }, ['vignette']),
  createSuperEffect('pro-super-cine-noir', 'Noir Contrast Extra', 'Classic monochrome dramatic gray scale.', Eye,
    { contrast: 1.45 }, [{ name: 'Contrast', key: 'contrast', type: 'number', min: 1, max: 2.2, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `grayscale(1) contrast(${params.contrast})`; }, ['vignette']),
  createSuperEffect('pro-super-cine-warm', 'Retro Cinema Warm Extra', 'Warm amber vintage film grading.', Film,
    { warmth: 0.28 }, [{ name: 'Warmth', key: 'warmth', type: 'number', min: 0.05, max: 0.8, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.warmth}) saturate(1.15)`; }, ['vignette']),
  createSuperEffect('pro-super-cine-cozy', 'Warm Cozy Tone Extra', 'Warm amber cozy lighting tint.', Sun,
    { amberFactor: 0.2 }, [{ name: 'Cozy Factor', key: 'amberFactor', type: 'number', min: 0.05, max: 0.6, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.amberFactor}) brightness(1.02)`; }, ['vignette']),
  createSuperEffect('pro-super-cine-arctic', 'Cool Arctic Blue Extra', 'Cold blue tone winter styling grade.', Moon,
    { blueCast: 1.15 }, [{ name: 'Blue Intensity', key: 'blueCast', type: 'number', min: 0.5, max: 2, step: 0.05 }],
    (ctx: any) => { ctx.filter = 'hue-rotate(6deg) saturate(0.95)'; }, ['vignette']),
  createSuperEffect('pro-super-cine-cyber', 'Cyberpunk Glow Extra', 'Flickering hot neon magenta shadow tint.', Sparkles,
    { sat: 1.25 }, [{ name: 'Saturate boost', key: 'sat', type: 'number', min: 0.8, max: 2, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `hue-rotate(-18deg) saturate(${params.sat})`; }, ['vignette']),
  createSuperEffect('pro-super-cine-forest', 'Moody Forest Green Extra', 'Deep emerald green color boost.', Palette,
    { greenBoost: 1.15 }, [{ name: 'Green Boost', key: 'greenBoost', type: 'number', min: 0.5, max: 2, step: 0.05 }],
    (ctx: any) => { ctx.filter = 'hue-rotate(10deg) saturate(1.12)'; }, ['vignette']),
  createSuperEffect('pro-super-cine-desert', 'Desert Sand Tone Extra', 'Warm dusty desert brown coloring.', Sun,
    { sandFactor: 0.35 }, [{ name: 'Sand Tint', key: 'sandFactor', type: 'number', min: 0.1, max: 0.8, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.sandFactor}) contrast(1.1)`; }, ['vignette']),
  createSuperEffect('pro-super-cine-vintage', 'Vintage LUT Color Extra', 'Classic faded vintage film stock coloring.', Film,
    { tone: 0.25 }, [{ name: 'LUT Tone', key: 'tone', type: 'number', min: 0.05, max: 0.7, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.tone}) saturate(1.1)`; }, ['vignette']),
  createSuperEffect('pro-super-cine-drama', 'Sepia Drama Look Extra', 'Nostalgic sepia look curve.', Film,
    { intensity: 0.48 }, [{ name: 'Sepia Level', key: 'intensity', type: 'number', min: 0.1, max: 0.9, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `sepia(${params.intensity}) contrast(1.15)`; }, ['vignette']),
  createSuperEffect('pro-super-cine-log', 'Documentary Flat Log Extra', 'Low contrast flat profile film log look.', Film,
    { flatFactor: 0.35 }, [{ name: 'Flat Curve', key: 'flatFactor', type: 'number', min: 0.1, max: 0.7, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `brightness(1.05) contrast(${1 - params.flatFactor}) saturate(0.82)`; }, ['vignette']),
  createSuperEffect('pro-super-cine-pastel', 'Pastel Dream Extra', 'Soft pastel look with reduced shadows.', Sparkles,
    { brightness: 1.12, contrast: 0.9 },
    [{ name: 'Brightness', key: 'brightness', type: 'number', min: 0.9, max: 1.35, step: 0.02 }, { name: 'Contrast', key: 'contrast', type: 'number', min: 0.6, max: 1.15, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `brightness(${params.brightness}) contrast(${params.contrast}) saturate(0.95)`; }, ['vignette']),
  createSuperEffect('pro-super-cine-indie', 'Indie Film Look Extra', 'Warm shadow cinematic aesthetic look.', Clapperboard,
    { warmShadows: 1.1 }, [{ name: 'Warm Shadows', key: 'warmShadows', type: 'number', min: 0.5, max: 2, step: 0.05 }],
    (ctx: any) => { ctx.filter = 'hue-rotate(3deg) saturate(1.05)'; }, ['vignette']),
  createSuperEffect('pro-super-cine-silver', 'Silver Classic Extra', 'Polished gray tone black & white grade.', Film,
    { contrast: 1.3 }, [{ name: 'Contrast', key: 'contrast', type: 'number', min: 0.8, max: 1.8, step: 0.05 }],
    (ctx: any, video: any, params: any) => { ctx.filter = `grayscale(1) contrast(${params.contrast}) brightness(1.02)`; }, ['vignette']),
  createSuperEffect('pro-super-cine-emerald', 'Emerald Cine Grade Extra', 'Deep forest green luxury cast.', Palette,
    { emeraldFactor: 1.15 }, [{ name: 'Emerald Level', key: 'emeraldFactor', type: 'number', min: 0.5, max: 2, step: 0.05 }],
    (ctx: any) => { ctx.filter = 'hue-rotate(15deg) saturate(1.08)'; }, ['vignette']),

  // ── GLITCH CATEGORY (15 effects) ──
  createSuperEffect('pro-super-glitch-tear', 'Screen Tear Extra', 'Horizontal signal synchronization tear spikes.', EyeOff,
    { tearWidth: 25 }, [{ name: 'Tear Width', key: 'tearWidth', type: 'number', min: 5, max: 80, step: 5 }],
    (ctx: any, video: any, params: any) => { if (Math.random() > 0.82) { ctx.translate((Math.random() - 0.5) * params.tearWidth, 0); } }, ['vignette']),
  createSuperEffect('pro-super-glitch-block', 'Block Corrupt Extra', 'Analogue data drop glitch blocks.', Zap,
    { rate: 0.18, size: 25 },
    [{ name: 'Corrupt Rate', key: 'rate', type: 'number', min: 0.05, max: 0.8, step: 0.05 }, { name: 'Block size', key: 'size', type: 'number', min: 5, max: 60, step: 2 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { if (Math.random() < params.rate) { ctx.fillStyle = 'rgba(0,0,255,0.15)'; ctx.fillRect(Math.random() * canvas.width, Math.random() * canvas.height, params.size * 2, params.size); } }, ['vignette']),
  createSuperEffect('pro-super-glitch-chrom', 'Chromatic Offset Extra', 'Fast chromatic aberration shifts.', Sliders,
    { shift: 8 }, [{ name: 'RGB Shift', key: 'shift', type: 'number', min: 2, max: 25, step: 1 }],
    (ctx: any) => { ctx.filter = 'saturate(1.05)'; }, ['vignette']),
  createSuperEffect('pro-super-glitch-invert', 'Inversion Flash Extra', 'Strobing inversion effect sweeps.', ShieldAlert,
    { frequency: 2.5 }, [{ name: 'Flash Speed', key: 'frequency', type: 'number', min: 0.5, max: 7, step: 0.5 }],
    (ctx: any, video: any, params: any, time: number) => { if ((time * params.frequency) % 1 < 0.1) { ctx.filter = 'invert(1)'; } }, ['negate']),
  createSuperEffect('pro-super-glitch-loss', 'Signal Loss Extra', 'Rolling signal loss sync shifts.', Radio,
    { rollSpeed: 1 }, [{ name: 'Sync Roll Speed', key: 'rollSpeed', type: 'number', min: 0.1, max: 3, step: 0.1 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { const dy = (time * params.rollSpeed * 60) % canvas.height; ctx.translate(0, dy * 0.1); }, ['crop=iw:ih-20:0:10']),
  createSuperEffect('pro-super-glitch-cable', 'Bad Cable TV Extra', 'White noise static line overlays.', Tv,
    { intensity: 0.3 }, [{ name: 'Static intensity', key: 'intensity', type: 'number', min: 0.05, max: 0.8, step: 0.05 }],
    (ctx: any) => { ctx.filter = 'contrast(1.06)'; }, ['vignette']),
  createSuperEffect('pro-super-glitch-strobe', 'Strobe Rainbow Extra', 'Rapid rainbow strobe hue flashes.', Zap,
    { speed: 5 }, [{ name: 'Flash Speed', key: 'speed', type: 'number', min: 1, max: 12, step: 0.5 }],
    (ctx: any, video: any, params: any, time: number) => { if (Math.sin(time * params.speed * 3) > 0.65) { ctx.filter = `hue-rotate(${time * 90}deg) saturate(1.15)`; } }, ['vignette']),
  createSuperEffect('pro-super-glitch-data', 'Data Noise Extra', 'Random analogue tracking line buzz.', Radio,
    { buzz: 8 }, [{ name: 'Buzz range', key: 'buzz', type: 'number', min: 2, max: 30, step: 1 }],
    (ctx: any, video: any, params: any) => { if (Math.random() < 0.28) { ctx.translate((Math.random() - 0.5) * params.buzz, 0); } }, ['vignette']),
  createSuperEffect('pro-super-glitch-scan', 'Scanline Jitter Extra', 'Automatic line alignment jitter.', EyeOff,
    { jitter: 12 }, [{ name: 'Jitter shift', key: 'jitter', type: 'number', min: 2, max: 35, step: 1 }],
    (ctx: any, video: any, params: any) => { ctx.translate((Math.random() - 0.5) * params.jitter, 0); }, ['crop=iw-20:ih:10:0']),
  createSuperEffect('pro-super-glitch-corrupt', 'Pixel Corrupt Extra', 'Blocky compression artifact glitches.', Zap,
    { corruption: 12 }, [{ name: 'Corruption factor', key: 'corruption', type: 'number', min: 2, max: 40, step: 1 }],
    (ctx: any) => { ctx.filter = 'contrast(1.08)'; }, ['vignette']),
  createSuperEffect('pro-super-glitch-broken', 'Broken LCD Extra', 'Broken LCD grid crack overlays.', Tv,
    { crackDensity: 5 }, [{ name: 'Crack Density', key: 'crackDensity', type: 'number', min: 1, max: 15, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(0.99)'; }, ['vignette']),
  createSuperEffect('pro-super-glitch-wave', 'Wave Jitter Extra', 'Wavy coordinate line sweep jitter.', Zap,
    { amplitude: 10 }, [{ name: 'Wave Amplitude', key: 'amplitude', type: 'number', min: 2, max: 35, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * 5.5) * params.amplitude; ctx.translate(dx, 0); }, ['crop=iw-16:ih:8:0']),
  createSuperEffect('pro-super-glitch-buzz', 'VHS Tape Buzz Extra', 'Analogue grain VHS head tracking.', Tv,
    { lines: 3 }, [{ name: 'Tracking lines', key: 'lines', type: 'number', min: 1, max: 10, step: 1 }],
    (ctx: any) => { ctx.filter = 'brightness(1.01)'; }, ['vignette']),
  createSuperEffect('pro-super-glitch-phase', 'Phase Shift Extra', 'Horizontal phase offset splits.', Zap,
    { displacement: 14 }, [{ name: 'Phase Shift', key: 'displacement', type: 'number', min: 2, max: 40, step: 1 }],
    (ctx: any) => { ctx.filter = 'saturate(1.04)'; }, ['vignette']),
  createSuperEffect('pro-super-glitch-holog', 'Corrupted Hologram Extra', 'Flickering cyan hologram scanlines.', Terminal,
    { opacity: 0.3 }, [{ name: 'Flicker Factor', key: 'opacity', type: 'number', min: 0.05, max: 0.8, step: 0.05 }],
    (ctx: any, video: any, params: any, time: number) => { if (Math.sin(time * 10) > 0.45) { ctx.fillStyle = `rgba(0,255,255, ${params.opacity * 0.2})`; ctx.fillRect(0,0,9999,9999); } }, ['vignette']),

  // ── CAMERA CATEGORY (15 effects) ──
  createSuperEffect('pro-super-cam-pan', 'Pan L to R Extra', 'Looping horizontal camera pan translation.', Move,
    { speed: 0.5, range: 25 }, [{ name: 'Pan Speed', key: 'speed', type: 'number', min: 0.1, max: 3, step: 0.1 }, { name: 'Drift Range', key: 'range', type: 'number', min: 5, max: 80, step: 5 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.range; ctx.translate(dx, 0); }, ['crop=iw-40:ih:20:0']),
  createSuperEffect('pro-super-cam-tilt', 'Tilt U to D Extra', 'Looping vertical tilt translation.', Move,
    { speed: 0.5, range: 20 }, [{ name: 'Tilt Speed', key: 'speed', type: 'number', min: 0.1, max: 3, step: 0.1 }, { name: 'Tilt Range', key: 'range', type: 'number', min: 5, max: 70, step: 5 }],
    (ctx: any, video: any, params: any, time: number) => { const dy = Math.cos(time * params.speed) * params.range; ctx.translate(0, dy); }, ['crop=iw:ih-36:0:18']),
  createSuperEffect('pro-super-cam-diag', 'Diagonal Sweep Extra', 'Diagonal panning camera motion sweeps.', Move,
    { speed: 0.7, offset: 20 }, [{ name: 'Sweep Speed', key: 'speed', type: 'number', min: 0.1, max: 3, step: 0.1 }, { name: 'Sweep Offset', key: 'offset', type: 'number', min: 5, max: 80, step: 5 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.offset; const dy = Math.cos(time * params.speed) * params.offset; ctx.translate(dx, dy); }, ['crop=iw-40:ih-40:20:20']),
  createSuperEffect('pro-super-cam-orbit', 'Orbit Tilt Extra', 'Orbital rotation tilt angle motion.', RefreshCw,
    { speed: 1, angle: 0.06 }, [{ name: 'Orbit Speed', key: 'speed', type: 'number', min: 0.1, max: 3, step: 0.1 }, { name: 'Tilt Angle', key: 'angle', type: 'number', min: 0.01, max: 0.3, step: 0.01 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { ctx.translate(canvas.width / 2, canvas.height / 2); ctx.rotate(Math.sin(time * params.speed) * params.angle); ctx.translate(-canvas.width / 2, -canvas.height / 2); }, ['rotate=0.03']),
  createSuperEffect('pro-super-cam-dolly', 'Dolly Zoom Extra', 'Smooth camera forward dolly zoom.', ZoomIn,
    { speed: 0.7, maxZoom: 1.25 }, [{ name: 'Speed', key: 'speed', type: 'number', min: 0.1, max: 3, step: 0.1 }, { name: 'Zoom Limit', key: 'maxZoom', type: 'number', min: 1.05, max: 2, step: 0.05 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { const currentZoom = 1 + (time * params.speed) % (params.maxZoom - 1); ctx.translate(canvas.width / 2, canvas.height / 2); ctx.scale(currentZoom, currentZoom); ctx.translate(-canvas.width / 2, -canvas.height / 2); }, ['scale=iw*1.1:ih*1.1,crop=iw/1.1:ih/1.1']),
  createSuperEffect('pro-super-cam-matrix', 'Matrix Warp Extra', 'Warping diagonal camera perspective angle.', Camera,
    { angle: 0.05 }, [{ name: 'Tilt Factor', key: 'angle', type: 'number', min: 0.01, max: 0.25, step: 0.01 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { ctx.translate(canvas.width / 2, canvas.height / 2); ctx.rotate(params.angle); ctx.translate(-canvas.width / 2, -canvas.height / 2); }, ['rotate=0.02']),
  createSuperEffect('pro-super-cam-hyper', 'Hyperlapse Shift Extra', 'Frame time steps shift hyperlapse.', RefreshCw,
    { speed: 1.8, shiftSteps: 6 }, [{ name: 'Lapse Speed', key: 'speed', type: 'number', min: 0.5, max: 5, step: 0.1 }, { name: 'Lapse Steps', key: 'shiftSteps', type: 'number', min: 2, max: 15, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const step = Math.floor(time * params.speed) % params.shiftSteps; ctx.translate(step * 2, 0); }, ['crop=iw-10:ih:5:0']),
  createSuperEffect('pro-super-cam-steady', 'Steadicam Float Extra', 'Smooth floating steadicam motion follow.', Eye,
    { speed: 1.2, damping: 3.5 }, [{ name: 'Speed', key: 'speed', type: 'number', min: 0.1, max: 3, step: 0.1 }, { name: 'Dampening', key: 'damping', type: 'number', min: 1, max: 15, step: 0.5 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.damping; ctx.translate(dx, 0); }, ['crop=iw-10:ih:5:0']),
  createSuperEffect('pro-super-cam-drone', 'Drone Pass Extra', 'Quad-copter drone pass horizontal panning.', Camera,
    { speed: 0.6, panFactor: 18 }, [{ name: 'Flight Speed', key: 'speed', type: 'number', min: 0.1, max: 2, step: 0.1 }, { name: 'Flight Drift', key: 'panFactor', type: 'number', min: 5, max: 60, step: 5 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { const dx = (time * params.speed * params.panFactor) % canvas.width; ctx.translate(-dx * 0.1, 0); }, ['crop=iw-16:ih:8:0']),
  createSuperEffect('pro-super-cam-handheld', 'Handheld Shake Extra', 'Human handheld holding camera shake.', Shuffle,
    { speed: 2.2, force: 5 }, [{ name: 'Frequency', key: 'speed', type: 'number', min: 0.5, max: 5, step: 0.1 }, { name: 'Shake Force', key: 'force', type: 'number', min: 1, max: 15, step: 0.5 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.force; const dy = Math.cos(time * params.speed * 0.8) * params.force; ctx.translate(dx, dy); }, ['crop=iw-10:ih-10:5:5']),
  createSuperEffect('pro-super-cam-shake', 'Shake Quick Extra', 'Action style brief shake camera zooms.', ZoomIn,
    { speed: 5, zoom: 1.12 }, [{ name: 'Shake Speed', key: 'speed', type: 'number', min: 1, max: 12, step: 0.5 }, { name: 'Zoom Limit', key: 'zoom', type: 'number', min: 1, max: 1.4, step: 0.02 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { const scale = 1 + Math.abs(Math.sin(time * params.speed)) * (params.zoom - 1); ctx.translate(canvas.width/2, canvas.height/2); ctx.scale(scale, scale); ctx.translate(-canvas.width/2, -canvas.height/2); }, ['scale=iw*1.12:ih*1.12,crop=iw/1.12:ih/1.12']),
  createSuperEffect('pro-super-cam-float', 'Smooth Float Extra', 'Slow floating vertical camera tilt pan.', Move,
    { speed: 0.4, height: 15 }, [{ name: 'Float Speed', key: 'speed', type: 'number', min: 0.1, max: 2, step: 0.1 }, { name: 'Float Height', key: 'height', type: 'number', min: 2, max: 40, step: 2 }],
    (ctx: any, video: any, params: any, time: number) => { const dy = Math.sin(time * params.speed) * params.height; ctx.translate(0, dy); }, ['crop=iw:ih-30:0:15']),
  createSuperEffect('pro-super-cam-quickwhip', 'Quick Whip Pan Extra', 'Aggressive whip panning motion sweeps.', Move,
    { speed: 4, force: 40 }, [{ name: 'Whip Speed', key: 'speed', type: 'number', min: 1, max: 10, step: 0.5 }, { name: 'Whip Force', key: 'force', type: 'number', min: 10, max: 120, step: 5 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.force; ctx.translate(dx, 0); }, ['crop=iw-80:ih:40:0']),
  createSuperEffect('pro-super-cam-crane', 'Crane Pan Extra', 'Horizontal sweeps mechanical crane lifts.', Move,
    { liftSpeed: 0.8, liftFactor: 18 }, [{ name: 'Crane Speed', key: 'liftSpeed', type: 'number', min: 0.1, max: 3, step: 0.1 }, { name: 'Crane Lift', key: 'liftFactor', type: 'number', min: 5, max: 50, step: 2 }],
    (ctx: any, video: any, params: any, time: number) => { const dy = Math.sin(time * params.liftSpeed) * params.liftFactor; ctx.translate(0, dy); }, ['crop=iw:ih-26:0:13']),
  createSuperEffect('pro-super-cam-slowdolly', 'Slow Dolly Extra', 'Automated slow dolly camera pan.', Move,
    { speed: 0.1, offsetRange: 30 }, [{ name: 'Dolly Speed', key: 'speed', type: 'number', min: 0.05, max: 1, step: 0.05 }, { name: 'Offset Range', key: 'offsetRange', type: 'number', min: 5, max: 80, step: 5 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.speed) * params.offsetRange; ctx.translate(dx, 0); }, ['crop=iw-40:ih:20:0']),

  // ── DISTORTION CATEGORY (10 effects) ──
  createSuperEffect('pro-super-dist-vert', 'Vertical Waves Extra', 'Wavy vertical offset coordinate lines.', RefreshCw,
    { frequency: 2.2, amplitude: 12 }, [{ name: 'Frequency', key: 'frequency', type: 'number', min: 0.5, max: 8, step: 0.1 }, { name: 'Amplitude', key: 'amplitude', type: 'number', min: 2, max: 35, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * params.frequency) * params.amplitude; ctx.translate(dx, 0); }, ['crop=iw-16:ih:8:0']),
  createSuperEffect('pro-super-dist-vortex', 'Vortex Warp Extra', 'Centred swirling spiral coordinate warp.', RefreshCw,
    { speed: 1.5, angle: 0.12 }, [{ name: 'Vortex Speed', key: 'speed', type: 'number', min: 0.1, max: 5, step: 0.1 }, { name: 'Vortex Angle', key: 'angle', type: 'number', min: 0.01, max: 0.4, step: 0.01 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { ctx.translate(canvas.width / 2, canvas.height / 2); ctx.rotate(Math.sin(time * params.speed) * params.angle); ctx.translate(-canvas.width / 2, -canvas.height / 2); }, ['rotate=0.04']),
  createSuperEffect('pro-super-dist-magnify', 'Magnify Glass Extra', 'Centred focal magnifying glass distortion.', ZoomIn,
    { zoom: 1.35 }, [{ name: 'Zoom factor', key: 'zoom', type: 'number', min: 1, max: 2.5, step: 0.05 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { ctx.translate(canvas.width / 2, canvas.height / 2); ctx.scale(params.zoom, params.zoom); ctx.translate(-canvas.width / 2, -canvas.height / 2); }, ['scale=iw*1.15:ih*1.15,crop=iw/1.15:ih/1.15']),
  createSuperEffect('pro-super-dist-melt', 'Pixel Melt Extra', 'Melt warp pixel translation down.', Shuffle,
    { speed: 2, scale: 16 }, [{ name: 'Melt Speed', key: 'speed', type: 'number', min: 0.5, max: 5, step: 0.1 }, { name: 'Melt Scale', key: 'scale', type: 'number', min: 2, max: 35, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const dy = Math.sin(time * params.speed) * params.scale; ctx.translate(0, dy); }, ['crop=iw:ih-16:0:8']),
  createSuperEffect('pro-super-dist-shear', 'Shear Warp Extra', 'Shearing perspective coordinates.', HelpCircle,
    { factor: 0.1 }, [{ name: 'Shear Force', key: 'factor', type: 'number', min: 0.01, max: 0.4, step: 0.01 }],
    (ctx: any, video: any, params: any, time: number, canvas: any) => { ctx.translate(canvas.width / 2, canvas.height / 2); ctx.rotate(params.factor); ctx.translate(-canvas.width / 2, -canvas.height / 2); }, ['rotate=0.02']),
  createSuperEffect('pro-super-dist-zigzag', 'Zigzag Warp Extra', 'Looping horizontal zigzag wave shift.', Shuffle,
    { peaks: 4, amplitude: 10 }, [{ name: 'Zigzag Peaks', key: 'peaks', type: 'number', min: 1, max: 10, step: 1 }, { name: 'Amplitude', key: 'amplitude', type: 'number', min: 2, max: 35, step: 1 }],
    (ctx: any, video: any, params: any, time: number) => { const dx = Math.sin(time * 2.5) * params.amplitude; ctx.translate(dx, 0); }, ['crop=iw-20:ih:10:0']),
  createSuperEffect('pro-super-dist-mirror', 'Fun Mirror Extra', 'Vertical screen split mirror distortion.', HelpCircle,
    { bend: 0.05 }, [{ name: 'Bend Factor', key: 'bend', type: 'number', min: 0.01, max: 0.25, step: 0.01 }],
    (ctx: any) => { ctx.filter = 'brightness(1.01)'; }, ['vignette']),
  createSuperEffect('pro-super-dist-kaleido4', '4-Way Kaleido Extra', 'Mirrored quadrant kaleidoscope coordinate warp.', Eye,
    { scale: 1 }, [{ name: 'Mirror Scale', key: 'scale', type: 'number', min: 0.5, max: 1.4, step: 0.1 }],
    (ctx: any) => { ctx.filter = 'brightness(1)'; }, ['vignette']),
  createSuperEffect('pro-super-dist-kaleido8', '8-Way Kaleido Extra', 'Mirrored octagonal kaleidoscope coordinate warp.', Eye,
    { scale: 1 }, [{ name: 'Mirror Scale', key: 'scale', type: 'number', min: 0.5, max: 1.4, step: 0.1 }],
    (ctx: any) => { ctx.filter = 'brightness(1)'; }, ['vignette']),
  createSuperEffect('pro-super-dist-skew', 'Skew Perspective Extra', 'Perspectives skew geometry warp.', Compass,
    { skewX: 0.08, skewY: 0.06 }, [{ name: 'Skew X', key: 'skewX', type: 'number', min: 0, max: 0.35, step: 0.01 }, { name: 'Skew Y', key: 'skewY', type: 'number', min: 0, max: 0.35, step: 0.01 }],
    (ctx: any, video: any, params: any) => { ctx.transform(1, params.skewY, params.skewX, 1, 0, 0); }, ['rotate=0.02'])
];
